splash screen added
Sochem/Sochem-App pull request #13
Opened 2021-10-16 08:20 UTC by Yatharth1301

2021-10-26 05:53 UTC, Arjupta requested changes
@Yatharth1301 Nice work but needs a lot of changes. PTAL at comments, also try to use the auto formatting provided by VSCode, it makes the code more readable.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
You have not included the change for pubspec.yaml file in this PR. As shared pref is a new dependency so you must include that too.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +                      return OnboardingScreen();
Don't use shortcuts like this. It will get confusing after auto formatting is applied, so introduce proper brackets.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +  var login = await prefs.getBool('isLoggedIn');
After awaiting for shared pref you don't have to write await infront of the pref.getSomething( ), remove the await from there.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +    print('in build');
Remove this debug print statement.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +    var textclr = new Color.fromRGBO(39,88,124,1);
These colors are constants and maybe used later on. So I would require you to create new constants for them and using those constants here. You can name the color constants as Blue1, Blue2 .. etc.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +                SizedBox(height:200),
This not the correct way to center any Widget. Your app will be used by different device sizes so it mus be responsive enough to handle it. 

Original design says that the sochem ison must be in the middle of the screen and the text should be placed between the  bottom of icon and bottom of the screen. So try to do this with some combination of widgets (Center, Container, Column, Row, etc.)

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +void setOnB() async{
Name this function correctly.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +}
The strings used here (isOnBoarded and isLoggenIn) should be stored as constants separately so that if we want to use the same shared pref somewhere else then we won't need to copy paste a same string value everywhere which can be error prone.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +    return Scaffold(
Make a different file for this screen, so that whenever a this screen is actuallly developed then the developer will only bother to change that single file instead of understanding your file.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +      appBar: AppBar(title:Center(child:Text('SOCHEM APP'))),
Make a different file for this screen, so that whenever a this screen is actuallly developed then the developer will only bother to change that single file instead of understanding your file.

2021-10-26 05:53 UTC, Arjupta commented on lib/screen/splashscreen.dart
> +    return Scaffold(
Make a different file for this screen, so that whenever a this screen is actuallly developed then the developer will only bother to change that single file instead of understanding your file.

2021-12-02 17:52 UTC, ARJUPTA commented on lib/screen/splashscreen.dart
> +                SizedBox(height:200),
@Yatharth1301 you still haven't resolved the issue I have mentioned in this comment.

2021-12-02 18:22 UTC, ARJUPTA commented
@Yatharth1301 you haven't done these few changes mentioned below
- You have to mention the issue number (in the PR description) which you have tried to solve here.
- You have not resolved one requested change at all, take a look at the comment where I have tagged you
- You have made the constant variables in the files only, I need you to mobe them to constants.dart and use them here
- Also you need to reply "Done" on all the changes that you have actually done.

2021-12-09 05:59 UTC, ARJUPTA commented
@Yatharth1301 Any updates

2021-12-09 08:38 UTC, Yatharth1301 commented on lib/screen/splashscreen.dart
> +                SizedBox(height:200),
@ARJUPTA changes done. Please Review

2021-12-13 09:21 UTC, ARJUPTA approved these changes
@Yatharth1301 I have made few extra changes for merging the demo files in your PR and the actual files in the codebase, take a look for better understanding.

2021-12-13 09:22 UTC, merged